version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db1
      - db2

  db1:
    image: postgres:13
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    volumes:
      - ./init_db1.sql:/docker-entrypoint-initdb.d/init_db1.sql

  db2:
    image: postgres:13
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    ports:
      - "5433:5432"
    volumes:
      - ./init_db2.sql:/docker-entrypoint-initdb.d/init_db2.sql