version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: thangnq2
      POSTGRES_PASSWORD: thangcoi123
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - mynetwork

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://thangnq2:thangcoi123@db:5432/postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge