CREATE TABLE IF NOT EXISTS PUBLIC.DATADICTIONARY (
    ID SERIAL PRIMARY KEY,
    DATAELEMENT VARCHAR(255) NOT NULL, 
    DESCRIPTION VARCHAR(255) NOT NULL,
    LEGAL_CONS VARCHAR(5000),
    DATATYPE VARCHAR(5000) NOT NULL,
    PII_STATUS VARCHAR(5) NOT NULL,
    CONFIDENTIAL_LEVEL VARCHAR(100) NOT NULL,
    ASSOCIATED_BUSINESSTERM VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.BUSINESSGLOSSARY (
    ID SERIAL PRIMARY KEY,
    BUSINESSTERM VARCHAR(255) NOT NULL, 
    DESCRIPTION VARCHAR(255) NOT NULL,
    ABBREVIATION VARCHAR(5000) NOT NULL,
    LINK_ASSET VARCHAR(5000)
);

CREATE TABLE IF NOT EXISTS PUBLIC.TECHNICALDATASTORAGE (
    ID SERIAL PRIMARY KEY,
    DATAELEMENT VARCHAR(255),
    TABLE_NAME VARCHAR(255) NOT NULL, 
    COLUMN_NAME VARCHAR(255) NOT NULL,
    SCHEMA_NAME VARCHAR(255) NOT NULL,
    DATATYPE VARCHAR(255) NOT NULL,
    source_field VARCHAR(255),
    source_table varchar(255),
    source_system varchar(255),
    mapping_rule varchar(1000),
    OWNER VARCHAR(255)
);

INSERT INTO PUBLIC.DATADICTIONARY 
(DATAELEMENT, DESCRIPTION, LEGAL_CONS, DATATYPE, PII_STATUS, CONFIDENTIAL_LEVEL, ASSOCIATED_BUSINESSTERM) VALUES
('PERSONALIDENTITY', 'SỐ GIẤY TỜ TÙY THÂN KHÁCH HÀNG', 'LUẬT CĂN CƯỚC', 'STRING', 'Y', 'PUBLIC', 'PII'),
('FULLNAME', 'HỌ VÀ TÊN ĐẦY ĐỦ', NULL, 'STRING', 'Y', 'CONFIDENTIAL', 'PII'),
('DOB', 'NGÀY SINH', NULL, 'STRING', 'Y', 'CONFIDENTIAL', 'PII');

INSERT INTO PUBLIC.BUSINESSGLOSSARY (ID, BUSINESSTERM, DESCRIPTION, ABBREVIATION, LINK_ASSET) VALUES
(1, 'ONEID', 'DỰ ÁN HỢP NHẤT KHÁCH HÀNG TẬP ĐOÀN', 'ONEID', 'HTTPS://WWW.LINKEDIN.COM/IN/NQT1310/'),
(2, 'HỆ SỐ THANH TOÁN NGẮN HẠN', 'ĐÁNH GIÁ KHẢ NĂNG THANH TOÁN CÁC KHOẢN NỢ NGẮN HẠN BẰNG TÀI SẢN NGẮN HẠN.', 'CR', NULL),
(3, 'HỆ SỐ THANH TOÁN NHANH', 'ĐÁNH GIÁ KHẢ NĂNG THANH TOÁN NỢ NGẮN HẠN BẰNG TIỀN VÀ CÁC KHOẢN TƯƠNG ĐƯƠNG TIỀN.', 'QR', NULL),
(4, 'KHẢ NĂNG THANH TOÁN LÃI VAY', 'ĐÁNH GIÁ KHẢ NĂNG TRẢ LÃI VAY TỪ LỢI NHUẬN TRƯỚC THUẾ VÀ LÃI.', 'TIE', NULL),
(5, 'HỆ SỐ TỰ TÀI TRỢ', 'ĐÁNH GIÁ MỨC ĐỘ TỰ CHỦ VỀ TÀI CHÍNH CỦA DOANH NGHIỆP.', 'DER', NULL),
(6, 'HỆ SỐ ĐÒN BẨY TÀI CHÍNH', 'THỂ HIỆN MỐI QUAN HỆ GIỮA NGUỒN VỐN VAY VÀ VỐN CHỦ SỞ HỮU.', 'FLR', NULL),
(7, 'TỶ SUẤT LỢI NHUẬN TRÊN DOANH THU', 'ĐÁNH GIÁ KHẢ NĂNG SINH LỜI TỪ DOANH THU.', 'ROS', NULL),
(8, 'TỶ SUẤT LỢI NHUẬN TRÊN TÀI SẢN', 'ĐÁNH GIÁ KHẢ NĂNG SINH LỜI TỪ TỔNG TÀI SẢN.', 'ROA', NULL),
(9, 'TỶ SUẤT LỢI NHUẬN TRÊN VỐN CHỦ SỞ HỮU', 'ĐÁNH GIÁ KHẢ NĂNG SINH LỜI TỪ VỐN CHỦ SỞ HỮU.', 'ROE', NULL),
(10, 'THÔNG TIN ĐỊNH DANH KHÁCH HÀNG', 'CÁC THÔNG TIN GTTT, GIỚI TÍNH, ĐỊA CHỈ, HỌ TÊN, SĐT, EMAIL', 'PII', NULL);
;
INSERT INTO TECHNICALDATASTORAGE (dataelement, TABLE_NAME, COLUMN_NAME, SCHEMA_NAME, DataType, source_field, source_table, source_system, mapping_rule, Owner)
VALUES 
('PERSONALIDENTITY', 'STG_CUS', 'NATID', 'STG', 'VARCHAR(255)', 'NATID', 'CUS', 'CORE', 'ONEID'),
('FULLNAME', 'STG_CUS', 'FULL_NAME', 'STG', 'VARCHAR(255)', 'NVL(EN_FULL_NAME,VN_FULL_NAME)', 'CUS', 'CORE', 'ONEID'),
('DOB', 'STG_CUS', 'DOB', 'STG', 'DATE', 'DOB', 'CUS', 'CORE', 'ONEID'),
('PERSONALIDENTITY', 'GOOD', 'NATID', 'DTL', 'VARCHAR(255)', 'NATID', 'CUS', 'CORE', 'ONEID'),
('FULLNAME', 'GOOD', 'FULL_NAME', 'DTL', 'VARCHAR(255)', 'NVL(EN_FULL_NAME,VN_FULL_NAME)', 'CUS', 'CORE', 'ONEID'),
('DOB', 'GOOD', 'DOB', 'DTL', 'DATE', 'DOB', 'CUS', 'CORE', 'ONEID'),
('PERSONALIDENTITY', 'CUS', 'NATID', 'DTL', 'VARCHAR(255)', NULL, NULL, 'CORE', NULL, 'ONEID'),
('FULLNAME', 'CUS', 'EN_FULL_NAME', 'DTL', 'VARCHAR(255)', NULL, NULL, 'CORE', NULL, 'ONEID'),
('DOB', 'CUS', 'DOB', 'DTL', 'DATE', NULL, NULL, 'CORE', NULL, 'ONEID');